### ISSUE TITLE
Adding generics to timed buf

### ISSUE THREAD

**Issue by lil5** [charithe/timedbuf#1]
Would @charithe be interested in a PR for adding a `/v2/` directory with a copy of timedbuf using generics

**Comment by charithe** [comment]
Oh wow! I haven't touched this for 8 years and had no idea anybody was using it. If you like to add generics, that's fine with me.

**Comment by lil5** [comment]
It'll be my weekend project, for another opensource project: https://github.com/lil5/tigerbeetle_api/tree/grpc 

Good to see you're up for receiving a PR, I'll be back 🚁 😎

**Comment by lil5** [comment]
Oops that took me no time at all, Looking forward to your review
